name: HTML Page Deployment Installation

on: push

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      #- run: sudo scp -o StrictHostKeyChecking=no -v nishanth.html -P ${{secrets.PASSWORD}} ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/html/

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "nishanth.html"
          target: "/home/nishanth/nishanth.html"
