name: Java workflow
on: [push]
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Java version
     run: java --version
 Execute:
  runs-on: ubuntu-latest
  needs: Build
  steps: 
   - uses: actions/checkout@v2
   - name: run java
     run: javac hello.java
