name: Java workflow
on: [push]
jobs:
 Build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: Java version
     run: java --version 
   - name: compile java
     run: javac hello.java
   - name: List the folders
     run: ls ${{github.workspace}}
   - name: run java
     run: java HelloWorld
